languageCode = 'en-us'
title = 'The Wild Wonderful World of Organic Geometry'
theme = 'charlie'
[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe=true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$']]
[params]
  math = true
  
